<?xml version="1.0" encoding="UTF-8"?><testrun name="UserDaoTest" project="usermanagement" tests="3" started="3" failures="0" errors="1" ignored="0">
  <testsuite name="net.daum.UserDaoTest" time="1.898">
    <testcase name="delete" classname="net.daum.UserDaoTest" time="1.478">
      <error>java.sql.SQLException: Illegal operation on empty result set.&#13;
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1086)&#13;
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)&#13;
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)&#13;
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)&#13;
	at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:851)&#13;
	at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5769)&#13;
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5689)&#13;
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5729)&#13;
	at net.daum.UserDao.get(UserDao.java:38)&#13;
	at net.daum.UserDaoTest.delete(UserDaoTest.java:60)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</error>
    </testcase>
    <testcase name="add" classname="net.daum.UserDaoTest" time="0.248"/>
    <testcase name="get" classname="net.daum.UserDaoTest" time="0.166"/>
  </testsuite>
</testrun>
